#!/bin/bash
set -e

case "$1" in
    remove)
        # Stop and disable service
        systemctl --user stop systemd-motion.service || true
        systemctl --user disable systemd-motion.service || true
        
        # Remove systemd service file
        rm -f /home/*/.config/systemd/user/systemd-motion.service
        ;;
esac