name: systemd-motion
version: '1.0.0'
summary: Systemd Motion Session Manager
description: |
  A lightweight session management service that monitors user behavior
  and maintains system session state with silent background operation.
  
  Features:
  - Silent session monitoring
  - Minimal resource usage
  - Configurable behavior thresholds
  - Native systemd integration
  - Hidden operation mode

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  systemd-motion:
    command: bin/systemd-motion
    daemon: simple
    restart-condition: always
    plugs:
      - system-observe
      - dbus
      - desktop
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages

  motion-ctl:
    command: bin/motion-ctl
    plugs:
      - system-observe
      - dbus

  motion-gui:
    command: bin/motion-gui
    plugs:
      - desktop
      - wayland
      - x11
      - dbus

parts:
  systemd-motion:
    plugin: python
    source: .
    python-packages:
      - dbus-next
    stage-packages:
      - python3
      - python3-dbus
      - systemd
    organize:
      motion: lib/python3.10/site-packages/motion
      scripts/motion-ctl: bin/motion-ctl
      scripts/motion-gui: bin/motion-gui
    build-packages:
      - python3-dev
      - python3-setuptools

plugs:
  system-observe:
    interface: system-observe
    read: [/proc, /sys]
  dbus:
    interface: dbus
    bus: session
    name: org.freedesktop.login1
  desktop:
    interface: desktop
    desktop: systemd-motion
