name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential devscripts debhelper
    
    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc
    
    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
        name: systemd-motion-deb
        path: ../systemd-motion_*.deb

  build-snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install snapcraft
      uses: snapcore/action-build@v1
      with:
        snapcraft-file: snap/snapcraft.yaml
    
    - name: Build Snap package
      run: snapcraft
    
    - name: Upload Snap package
      uses: actions/upload-artifact@v3
      with:
        name: systemd-motion-snap
        path: systemd-motion_*.snap

  release:
    needs: [build-deb, build-snap]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          systemd-motion-deb/*.deb
          systemd-motion-snap/*.snap
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
